/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blaze-projects': BlazeProject;
    'kolasi-events': KolasiEvent;
    artists: Artist;
    milestones: Milestone;
    inquiries: Inquiry;
    pages: Page;
    'venue-packages': VenuePackage;
    'case-studies': CaseStudy;
    'venue-faq': VenueFaq;
    'venue-inquiries': VenueInquiry;
    'venue-seo-pages': VenueSeoPage;
    testimonials: Testimonial;
    posts: Post;
    'pricing-factors': PricingFactor;
    'admin-alerts': AdminAlert;
    'automation-sequences': AutomationSequence;
    'sent-notifications': SentNotification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blaze-projects': BlazeProjectsSelect<false> | BlazeProjectsSelect<true>;
    'kolasi-events': KolasiEventsSelect<false> | KolasiEventsSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'venue-packages': VenuePackagesSelect<false> | VenuePackagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'venue-faq': VenueFaqSelect<false> | VenueFaqSelect<true>;
    'venue-inquiries': VenueInquiriesSelect<false> | VenueInquiriesSelect<true>;
    'venue-seo-pages': VenueSeoPagesSelect<false> | VenueSeoPagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'pricing-factors': PricingFactorsSelect<false> | PricingFactorsSelect<true>;
    'admin-alerts': AdminAlertsSelect<false> | AdminAlertsSelect<true>;
    'automation-sequences': AutomationSequencesSelect<false> | AutomationSequencesSelect<true>;
    'sent-notifications': SentNotificationsSelect<false> | SentNotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'global-settings': GlobalSetting;
    'press-kit': PressKit;
    showreel: Showreel;
  };
  globalsSelect: {
    'global-settings': GlobalSettingsSelect<false> | GlobalSettingsSelect<true>;
    'press-kit': PressKitSelect<false> | PressKitSelect<true>;
    showreel: ShowreelSelect<false> | ShowreelSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Admins can manage users and delete content. Editors can create and edit content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blaze-projects".
 */
export interface BlazeProject {
  id: string;
  title: string;
  /**
   * Auto-generated from title if left blank
   */
  slug?: string | null;
  category: 'wedding' | 'editorial' | 'event' | 'documentary' | 'diplomatic';
  heroVideo?: {
    /**
     * Where the video is hosted
     */
    videoSource?: ('mux' | 'cloudinary') | null;
    muxPlaybackId?: string | null;
    muxAssetId?: string | null;
    /**
     * Cloudinary public ID (e.g. sg-platform/videos/my-video)
     */
    cloudinaryVideoId?: string | null;
    posterUrl?: string | null;
  };
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. STOUH BEIRUT, Embassy of Lebanon
   */
  client?: string | null;
  date?: string | null;
  /**
   * e.g. Paris, Cannes, Beirut
   */
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show on homepage carousel
   */
  featured?: boolean | null;
  /**
   * Show "Coming Soon" badge instead of link
   */
  comingSoon?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kolasi-events".
 */
export interface KolasiEvent {
  id: string;
  title: string;
  slug?: string | null;
  eventType?: ('club' | 'festival' | 'private' | 'corporate' | 'rooftop') | null;
  /**
   * e.g. Le Speakeasy Paris
   */
  venue?: string | null;
  date?: string | null;
  artists?: (string | Artist)[] | null;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        title?: string | null;
        videoSource?: ('mux' | 'cloudinary') | null;
        muxPlaybackId?: string | null;
        /**
         * Cloudinary public ID (e.g. sg-platform/videos/my-video)
         */
        cloudinaryVideoId?: string | null;
        /**
         * Loop point in seconds (e.g. 22)
         */
        loopEnd?: number | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('upcoming' | 'past' | 'cancelled') | null;
  /**
   * URL to ticket platform (Shotgun, Dice, Eventbrite, etc.)
   */
  ticketUrl?: string | null;
  /**
   * e.g. "23:00"
   */
  doorsTime?: string | null;
  /**
   * e.g. "06:00"
   */
  endTime?: string | null;
  /**
   * e.g. "15€ / 20€ at door"
   */
  ticketPrice?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: string;
  name: string;
  slug?: string | null;
  photo?: (string | null) | Media;
  /**
   * 2–3 sentences
   */
  bio?: string | null;
  genres?:
    | {
        genre: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    instagram?: string | null;
    soundcloud?: string | null;
    spotify?: string | null;
  };
  mixes?:
    | {
        title: string;
        url: string;
        platform?: ('soundcloud' | 'mixcloud' | 'spotify' | 'youtube') | null;
        /**
         * e.g. 1:23:45
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Appears in homepage gallery band
   */
  featured?: boolean | null;
  /**
   * Category for /venues roster display
   */
  rosterCategory?: ('resident' | 'headliner' | 'live-act' | 'hybrid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: string;
  title: string;
  description: string;
  brand?: ('blaze' | 'kolasi' | 'both' | 'personal') | null;
  /**
   * Lower numbers appear first
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  service?: ('wedding-film' | 'editorial-commercial' | 'event-production' | 'dj-performance' | 'hybrid-package') | null;
  /**
   * Freeform timeframe from user
   */
  eventDate?: string | null;
  guestCount?: number | null;
  /**
   * Freeform, e.g. EUR 5,000–10,000
   */
  budget?: string | null;
  details?: string | null;
  source: 'contact-page' | 'quote-page';
  status?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  /**
   * Private notes — not visible to client
   */
  internalNotes?: string | null;
  /**
   * Auto-calculated lead score (0-100)
   */
  leadScore?: number | null;
  leadTier?: ('hot' | 'warm' | 'cool' | 'cold') | null;
  /**
   * Estimated deal value in EUR
   */
  estimatedValue?: number | null;
  /**
   * When this lead was last contacted
   */
  lastContactedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Internal label
   */
  title: string;
  /**
   * Matches route: home, blaze, kolasi, about, contact, quote
   */
  slug: string;
  /**
   * Browser tab + Google title (50–60 chars)
   */
  seoTitle?: string | null;
  /**
   * Meta description (120–155 chars)
   */
  seoDescription?: string | null;
  /**
   * 1200x630 recommended
   */
  ogImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-packages".
 */
export interface VenuePackage {
  id: string;
  /**
   * e.g. "Starter", "Core", "Flagship"
   */
  name: string;
  tier: 'starter' | 'core' | 'flagship';
  /**
   * e.g. "For venues testing the waters"
   */
  tagline?: string | null;
  whoItsFor?: string | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "€1,500–3,000/mo"
   */
  priceRange?: string | null;
  /**
   * Visually highlighted card
   */
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  venueName: string;
  /**
   * URL: /venues/case-studies/[slug]
   */
  slug: string;
  coverImage?: (string | null) | Media;
  /**
   * Where the cover video is hosted
   */
  coverVideoSource?: ('mux' | 'cloudinary') | null;
  /**
   * Mux playback ID
   */
  coverVideo?: string | null;
  /**
   * Cloudinary public ID (e.g. sg-platform/videos/my-video)
   */
  coverVideoCloudinaryId?: string | null;
  /**
   * e.g. "Booking / DA / Content"
   */
  role?: string | null;
  /**
   * e.g. "3 nights/week"
   */
  frequency?: string | null;
  /**
   * What was delivered
   */
  deliverables?: string | null;
  /**
   * 1 measurable result
   */
  outcome?: string | null;
  /**
   * Full content for the detail page
   */
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-faq".
 */
export interface VenueFaq {
  id: string;
  question: string;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-inquiries".
 */
export interface VenueInquiry {
  id: string;
  venueName: string;
  address?: string | null;
  website?: string | null;
  instagram?: string | null;
  venueType?: ('bar' | 'brasserie' | 'club' | 'resto-festif' | 'hybrid') | null;
  capacity?: number | null;
  hasDancePocket?: boolean | null;
  /**
   * "Do you currently have DJ nights?"
   */
  currentProgramming?: string | null;
  goal?: ('more-tables' | 'better-crowd' | 'stronger-brand' | 'higher-spend' | 'signature-night')[] | null;
  monthlyBudget: 'under-2k' | '2k-5k' | '5k-10k' | '10k-plus';
  decisionMaker?: ('owner' | 'gm' | 'event-manager') | null;
  contactName: string;
  contactWhatsApp: string;
  contactEmail: string;
  timeline?: ('asap' | 'next-month' | 'next-season') | null;
  roomPhotos?:
    | {
        photo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  source?: ('venue-form' | 'deck-download') | null;
  status?: ('new' | 'qualified' | 'call-booked' | 'proposal-sent' | 'signed' | 'disqualified') | null;
  /**
   * Internal notes — not visible to the client
   */
  internalNotes?: string | null;
  /**
   * Auto-calculated lead score (0-100)
   */
  leadScore?: number | null;
  leadTier?: ('hot' | 'warm' | 'cool' | 'cold') | null;
  /**
   * Estimated deal value in EUR
   */
  estimatedValue?: number | null;
  /**
   * When this lead was last contacted
   */
  lastContactedAt?: string | null;
  /**
   * Actual contract value (EUR). Auto-estimated, editable.
   */
  contractValue?: number | null;
  /**
   * Estimated monthly retainer value (EUR)
   */
  monthlyValue?: number | null;
  /**
   * Projected 12-month value (EUR)
   */
  annualValue?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-seo-pages".
 */
export interface VenueSeoPage {
  id: string;
  /**
   * H1 heading for the page
   */
  title: string;
  /**
   * URL: /venues/[slug] — e.g. dj-booking-paris
   */
  slug: string;
  /**
   * Primary SEO keyword — e.g. "DJ booking Paris"
   */
  targetKeyword?: string | null;
  /**
   * Meta title (50–60 chars)
   */
  seoTitle?: string | null;
  /**
   * Meta description (120–155 chars)
   */
  seoDescription?: string | null;
  /**
   * Subtitle under the H1
   */
  heroSubtitle?: string | null;
  /**
   * Main body content (800–1200 words)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  /**
   * 1200x630 OG image
   */
  ogImage?: (string | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  clientName: string;
  /**
   * e.g. "Bride", "Venue Owner", "Event Director"
   */
  role?: string | null;
  brand: 'blaze' | 'kolasi' | 'venues' | 'personal';
  quote: string;
  rating?: number | null;
  photo?: (string | null) | Media;
  /**
   * Link this testimonial to a specific project
   */
  projectLink?: (string | null) | BlazeProject;
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Appears on listing pages and in social shares
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'behind-the-scenes' | 'tips' | 'industry' | 'news' | 'client-stories';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  coverImage?: (string | null) | Media;
  author?: (string | null) | User;
  publishedAt: string;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-factors".
 */
export interface PricingFactor {
  id: string;
  service: 'wedding-film' | 'editorial-commercial' | 'dj-performance' | 'event-production';
  /**
   * e.g. "Hours of Coverage", "Number of Cameras"
   */
  factorName: string;
  factorType: 'slider' | 'toggle' | 'select';
  /**
   * Base price in EUR for this factor
   */
  basePrice: number;
  /**
   * Options for select/slider type factors
   */
  options?:
    | {
        label: string;
        value: string;
        /**
         * Price multiplier (e.g. 1.5 = 150% of base)
         */
        multiplier: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Minimum value for slider type
   */
  sliderMin?: number | null;
  /**
   * Maximum value for slider type
   */
  sliderMax?: number | null;
  /**
   * Step increment for slider
   */
  sliderStep?: number | null;
  /**
   * Display unit (e.g. "hours", "cameras")
   */
  unit?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-alerts".
 */
export interface AdminAlert {
  id: string;
  title: string;
  message?: string | null;
  type: 'new-lead' | 'hot-lead' | 'stale-lead' | 'status-change' | 'deal-closed' | 'sequence-failed' | 'system';
  severity: 'info' | 'warning' | 'urgent';
  /**
   * Link to general inquiry
   */
  inquiry?: (string | null) | Inquiry;
  /**
   * Link to venue inquiry
   */
  venueInquiry?: (string | null) | VenueInquiry;
  isRead?: boolean | null;
  /**
   * Auto-set when marked as read
   */
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-sequences".
 */
export interface AutomationSequence {
  id: string;
  name: string;
  triggerType: 'on-create' | 'on-status-change' | 'on-stale';
  triggerCollection: 'inquiries' | 'venue-inquiries' | 'both';
  /**
   * Which status triggers this sequence
   */
  triggerStatus?:
    | (
        | 'new'
        | 'contacted'
        | 'booked'
        | 'closed'
        | 'qualified'
        | 'call-booked'
        | 'proposal-sent'
        | 'signed'
        | 'disqualified'
      )
    | null;
  /**
   * Hours to wait before sending (0 = immediate)
   */
  delayHours: number;
  channels: ('email' | 'whatsapp' | 'admin-alert')[];
  /**
   * Supports {{name}}, {{venueName}}, etc.
   */
  emailSubject?: string | null;
  /**
   * Email template body. HTML allowed (admin-authored). Supports {{name}}, {{email}}, {{venueName}}, {{calendlyUrl}}, etc. Variable values are HTML-escaped at send time.
   */
  emailBody?: string | null;
  /**
   * WhatsApp message template with variables
   */
  whatsappMessage?: string | null;
  targetAudience: 'admin' | 'lead' | 'both';
  /**
   * Toggle on/off without deleting
   */
  isActive?: boolean | null;
  /**
   * Sequence order (1st, 2nd, 3rd follow-up)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sent-notifications".
 */
export interface SentNotification {
  id: string;
  /**
   * Which sequence triggered this notification
   */
  sequence?: (string | null) | AutomationSequence;
  /**
   * Which general inquiry
   */
  inquiryRef?: (string | null) | Inquiry;
  /**
   * Which venue inquiry
   */
  venueInquiryRef?: (string | null) | VenueInquiry;
  channel: 'email' | 'whatsapp' | 'admin-alert';
  /**
   * When this notification is due to fire. Set at queue time. Cron filters by scheduledFor <= now.
   */
  scheduledFor?: string | null;
  /**
   * When notification was actually sent (or attempted)
   */
  sentAt?: string | null;
  status: 'pending' | 'sent' | 'failed';
  /**
   * Error details if send failed
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blaze-projects';
        value: string | BlazeProject;
      } | null)
    | ({
        relationTo: 'kolasi-events';
        value: string | KolasiEvent;
      } | null)
    | ({
        relationTo: 'artists';
        value: string | Artist;
      } | null)
    | ({
        relationTo: 'milestones';
        value: string | Milestone;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'venue-packages';
        value: string | VenuePackage;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'venue-faq';
        value: string | VenueFaq;
      } | null)
    | ({
        relationTo: 'venue-inquiries';
        value: string | VenueInquiry;
      } | null)
    | ({
        relationTo: 'venue-seo-pages';
        value: string | VenueSeoPage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pricing-factors';
        value: string | PricingFactor;
      } | null)
    | ({
        relationTo: 'admin-alerts';
        value: string | AdminAlert;
      } | null)
    | ({
        relationTo: 'automation-sequences';
        value: string | AutomationSequence;
      } | null)
    | ({
        relationTo: 'sent-notifications';
        value: string | SentNotification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blaze-projects_select".
 */
export interface BlazeProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  heroVideo?:
    | T
    | {
        videoSource?: T;
        muxPlaybackId?: T;
        muxAssetId?: T;
        cloudinaryVideoId?: T;
        posterUrl?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  client?: T;
  date?: T;
  location?: T;
  description?: T;
  featured?: T;
  comingSoon?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kolasi-events_select".
 */
export interface KolasiEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  venue?: T;
  date?: T;
  artists?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        videoSource?: T;
        muxPlaybackId?: T;
        cloudinaryVideoId?: T;
        loopEnd?: T;
        id?: T;
      };
  description?: T;
  status?: T;
  ticketUrl?: T;
  doorsTime?: T;
  endTime?: T;
  ticketPrice?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  genres?:
    | T
    | {
        genre?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        instagram?: T;
        soundcloud?: T;
        spotify?: T;
      };
  mixes?:
    | T
    | {
        title?: T;
        url?: T;
        platform?: T;
        duration?: T;
        id?: T;
      };
  featured?: T;
  rosterCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  brand?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  eventDate?: T;
  guestCount?: T;
  budget?: T;
  details?: T;
  source?: T;
  status?: T;
  internalNotes?: T;
  leadScore?: T;
  leadTier?: T;
  estimatedValue?: T;
  lastContactedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-packages_select".
 */
export interface VenuePackagesSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  tagline?: T;
  whoItsFor?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  priceRange?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  venueName?: T;
  slug?: T;
  coverImage?: T;
  coverVideoSource?: T;
  coverVideo?: T;
  coverVideoCloudinaryId?: T;
  role?: T;
  frequency?: T;
  deliverables?: T;
  outcome?: T;
  fullContent?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-faq_select".
 */
export interface VenueFaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-inquiries_select".
 */
export interface VenueInquiriesSelect<T extends boolean = true> {
  venueName?: T;
  address?: T;
  website?: T;
  instagram?: T;
  venueType?: T;
  capacity?: T;
  hasDancePocket?: T;
  currentProgramming?: T;
  goal?: T;
  monthlyBudget?: T;
  decisionMaker?: T;
  contactName?: T;
  contactWhatsApp?: T;
  contactEmail?: T;
  timeline?: T;
  roomPhotos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  source?: T;
  status?: T;
  internalNotes?: T;
  leadScore?: T;
  leadTier?: T;
  estimatedValue?: T;
  lastContactedAt?: T;
  contractValue?: T;
  monthlyValue?: T;
  annualValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-seo-pages_select".
 */
export interface VenueSeoPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  targetKeyword?: T;
  seoTitle?: T;
  seoDescription?: T;
  heroSubtitle?: T;
  content?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  ogImage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  role?: T;
  brand?: T;
  quote?: T;
  rating?: T;
  photo?: T;
  projectLink?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  author?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-factors_select".
 */
export interface PricingFactorsSelect<T extends boolean = true> {
  service?: T;
  factorName?: T;
  factorType?: T;
  basePrice?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        multiplier?: T;
        id?: T;
      };
  sliderMin?: T;
  sliderMax?: T;
  sliderStep?: T;
  unit?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-alerts_select".
 */
export interface AdminAlertsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  severity?: T;
  inquiry?: T;
  venueInquiry?: T;
  isRead?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-sequences_select".
 */
export interface AutomationSequencesSelect<T extends boolean = true> {
  name?: T;
  triggerType?: T;
  triggerCollection?: T;
  triggerStatus?: T;
  delayHours?: T;
  channels?: T;
  emailSubject?: T;
  emailBody?: T;
  whatsappMessage?: T;
  targetAudience?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sent-notifications_select".
 */
export interface SentNotificationsSelect<T extends boolean = true> {
  sequence?: T;
  inquiryRef?: T;
  venueInquiryRef?: T;
  channel?: T;
  scheduledFor?: T;
  sentAt?: T;
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-settings".
 */
export interface GlobalSetting {
  id: string;
  phone?: string | null;
  email?: string | null;
  instagramLinks?:
    | {
        handle: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  seoDefaults?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (string | null) | Media;
  };
  responsePromise?: string | null;
  /**
   * Calendly booking link for venue discovery calls
   */
  calendlyUrl?: string | null;
  /**
   * WhatsApp number shown on /venues page
   */
  whatsappNumber?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit".
 */
export interface PressKit {
  id: string;
  shortBio?: string | null;
  mediumBio?: string | null;
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logos?:
    | {
        brand?: ('sg' | 'blaze' | 'kolasi') | null;
        file: string | Media;
        format?: ('svg' | 'png' | 'eps') | null;
        variant?: ('light' | 'dark' | 'color') | null;
        id?: string | null;
      }[]
    | null;
  pressPhotos?:
    | {
        image: string | Media;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  mediaAppearances?:
    | {
        title: string;
        publication: string;
        url?: string | null;
        date?: string | null;
        type?: ('article' | 'interview' | 'feature' | 'podcast' | 'video') | null;
        id?: string | null;
      }[]
    | null;
  pressContact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel".
 */
export interface Showreel {
  id: string;
  heroReel?: {
    videoSource?: ('mux' | 'cloudinary') | null;
    muxPlaybackId?: string | null;
    /**
     * Cloudinary public ID
     */
    cloudinaryVideoId?: string | null;
    posterUrl?: string | null;
    title?: string | null;
  };
  highlights?:
    | {
        title: string;
        videoSource?: ('mux' | 'cloudinary') | null;
        muxPlaybackId?: string | null;
        /**
         * Cloudinary public ID
         */
        cloudinaryVideoId?: string | null;
        posterUrl?: string | null;
        category?: ('wedding' | 'editorial' | 'event' | 'music' | 'brand') | null;
        linkedProject?: (string | null) | BlazeProject;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-settings_select".
 */
export interface GlobalSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  instagramLinks?:
    | T
    | {
        handle?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  responsePromise?: T;
  calendlyUrl?: T;
  whatsappNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit_select".
 */
export interface PressKitSelect<T extends boolean = true> {
  shortBio?: T;
  mediumBio?: T;
  fullBio?: T;
  logos?:
    | T
    | {
        brand?: T;
        file?: T;
        format?: T;
        variant?: T;
        id?: T;
      };
  pressPhotos?:
    | T
    | {
        image?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  mediaAppearances?:
    | T
    | {
        title?: T;
        publication?: T;
        url?: T;
        date?: T;
        type?: T;
        id?: T;
      };
  pressContact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel_select".
 */
export interface ShowreelSelect<T extends boolean = true> {
  heroReel?:
    | T
    | {
        videoSource?: T;
        muxPlaybackId?: T;
        cloudinaryVideoId?: T;
        posterUrl?: T;
        title?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        videoSource?: T;
        muxPlaybackId?: T;
        cloudinaryVideoId?: T;
        posterUrl?: T;
        category?: T;
        linkedProject?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}